version: '3.1'

services:
  db:
    platform: linux/arm64
    image: mysql/mysql-server:8.0.23
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: moser
      MYSQL_ROOT_HOST: '%'
    volumes:
      - moser_data:/var/lib/mysql

volumes:
  moser_data: