server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vinyl?allowPublicKeyRetrievel=true&sslMode=DISABLED&createDatabaseIfNotExist=true
    username: root
    password: moser
  jpa:
    hibernate:
      ddl-auto: update
