server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vinyl?createDatabaseIfNotExist=true
    username: root
    password: moser
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hinernate:
        SQL: DEBUG
